// <auto-generated />
using System;
using E_commerce_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerce_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924120445_ADD_3Culm_Refresh_in_User")]
    partial class ADD_3Culm_Refresh_in_User
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerce_API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            ProductId = 1,
                            ShoppingCartId = 1,
                            quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            ProductId = 3,
                            ShoppingCartId = 1,
                            quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            ProductId = 4,
                            ShoppingCartId = 2,
                            quantity = 3
                        });
                });

            modelBuilder.Entity("E_commerce_API.Models.Categore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categore");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Description = "Men and women clothes",
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Description = "Home and kitchen appliances",
                            Name = "Home Appliances"
                        });
                });

            modelBuilder.Entity("E_commerce_API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("shippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("stutes")
                        .HasColumnType("int");

                    b.Property<decimal>("totalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            UserId = 2,
                            shippingAddress = "Cairo, Egypt",
                            stutes = 3,
                            totalPrice = 50000m
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            UserId = 3,
                            shippingAddress = "Giza, Egypt",
                            stutes = 1,
                            totalPrice = 1800m
                        });
                });

            modelBuilder.Entity("E_commerce_API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("priceAtPurchase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            priceAtPurchase = 45000m
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 2,
                            priceAtPurchase = 2500m
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 3,
                            priceAtPurchase = 600m
                        });
                });

            modelBuilder.Entity("E_commerce_API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoreId");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("Price");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoreId = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Description = "Apple iPhone 15 128GB",
                            IsAvailable = true,
                            Name = "iPhone 15",
                            Price = 45000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoreId = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Description = "Samsung Galaxy S24 256GB",
                            IsAvailable = true,
                            Name = "Samsung Galaxy S24",
                            Price = 35000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoreId = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Description = "Bluetooth wireless headphones",
                            IsAvailable = true,
                            Name = "Wireless Headphones",
                            Price = 2500m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoreId = 2,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Description = "Cotton T-Shirt",
                            IsAvailable = true,
                            Name = "T-Shirt",
                            Price = 600m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoreId = 3,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Description = "Automatic coffee machine",
                            IsAvailable = true,
                            Name = "Coffee Machine",
                            Price = 5000m,
                            Stock = 8
                        });
                });

            modelBuilder.Entity("E_commerce_API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            OrderId = 1,
                            ProductId = 1,
                            UserId = 2,
                            comment = "Excellent product and very good quality.",
                            rate = 9
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            OrderId = 2,
                            ProductId = 4,
                            UserId = 3,
                            comment = "Good quality and comfortable.",
                            rate = 8
                        });
                });

            modelBuilder.Entity("E_commerce_API.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("E_commerce_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenRevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Email = "admin@example.com",
                            IsActive = true,
                            Password = "Admin123",
                            Phone = "01012345678",
                            Role = 2,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Email = "moaz@example.com",
                            IsActive = true,
                            Password = "Customer123",
                            Phone = "01112345678",
                            Role = 1,
                            UserName = "MoazAhmed"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2026, 9, 24, 12, 4, 45, 249, DateTimeKind.Utc).AddTicks(4676),
                            CreateBy = "System",
                            Email = "ahmed@example.com",
                            IsActive = true,
                            Password = "Customer456",
                            Phone = "01212345678",
                            Role = 1,
                            UserName = "AhmedAli"
                        });
                });

            modelBuilder.Entity("E_commerce_API.Models.CartItem", b =>
                {
                    b.HasOne("E_commerce_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerce_API.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("E_commerce_API.Models.Order", b =>
                {
                    b.HasOne("E_commerce_API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_commerce_API.Models.OrderItem", b =>
                {
                    b.HasOne("E_commerce_API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerce_API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_commerce_API.Models.Product", b =>
                {
                    b.HasOne("E_commerce_API.Models.Categore", "Categore")
                        .WithMany("Products")
                        .HasForeignKey("CategoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categore");
                });

            modelBuilder.Entity("E_commerce_API.Models.Review", b =>
                {
                    b.HasOne("E_commerce_API.Models.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("E_commerce_API.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerce_API.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_commerce_API.Models.ShoppingCart", b =>
                {
                    b.HasOne("E_commerce_API.Models.User", "User")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("E_commerce_API.Models.ShoppingCart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_commerce_API.Models.Categore", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_commerce_API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("E_commerce_API.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("E_commerce_API.Models.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("E_commerce_API.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("ShoppingCart")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
